version: '3.8'

services:
  sabersim-extractor:
    build: .
    container_name: sabersim-extractor
    volumes:
      # Mount your HAR files directory
      - ./har_files:/app/har_files:ro
      # Mount data output directory
      - ./_data:/app/_data
      # Mount source code for development (optional)
      - ./src:/app/src:ro
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    command: ["python", "src/sabersim/atoms/extractors/extract.py", "--help"]

  # Development service with interactive shell
  sabersim-dev:
    build: .
    container_name: sabersim-dev
    volumes:
      - ./har_files:/app/har_files:ro
      - ./_data:/app/_data
      - ./src:/app/src:ro
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
